# Use a imagem base do Python
FROM python:3.10

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie os arquivos necessários para o contêiner
COPY requirements.txt /app/
COPY bot.py /app/

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Comando para executar o bot quando o contêiner for iniciado
CMD ["python", "bot.py"]
